example.property: "DEV"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://database:5432/customers_dev"
spring.datasource.username: "postgres"
spring.datasource.password: "{cipher}20c39bea870275c12ef85b8e7f64ac7b54f81f7ea628cd99db5fc14508029d6a"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"